src/myportfolio/urls.py
from django.urls import path
from . views import experiences, index, send_message
urlpatterns = [
    path('', index, name="index"),
    path('contact/', send_message, name="send_message"),
    path('experience/', experiences, name="experiences"),



]

src/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myportfolio.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/myportfolio/models.py
from django.db import models

# Section Accueil (home)


class Home(models.Model):
    name = models.CharField(max_length=30)
    greetings_1 = models.CharField(max_length=10)
    greetings_2 = models.CharField(max_length=10)
    picture = models.ImageField(upload_to='picture/')
# save time when modified
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

    
# Section à propos de (about)

class About(models.Model):
    heading = models.CharField(max_length=60)
    career = models.CharField(max_length=30)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.career  
    
    
class Profile(models.Model):
    About = models.ForeignKey(About, on_delete=models.SET_NULL, null=True, blank=True)
    social_name = models.CharField(max_length=20)
    link = models.URLField(max_length=300) 
  
# Section de competence (skills)


class Category(models.Model):

    name = models.CharField(max_length=30)
    
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Skill"
        verbose_name_plural = "Skills"
        
    def __str__(self):
        return self.name 


class Skills(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=30)



# portfolio section 


class Portfolio(models.Model):
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=300)
    
    def __str__(self):
        return f"Portfolio {self.id}"


# portfolio Message


class PorfolioMessage(models.Model):
    nom = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()


    class Meta:
        verbose_name = "Message"
        
    def __str__(self):
        return self.nom
    
# Experience professionelle
    
class Experiences(models.Model):
    experience_name = models.CharField(max_length=100)
    experience_Post = models.CharField(max_length=100)
    experience_description = models.TextField()
    experience_img = models.ImageField(upload_to='experience/')
   


    class Meta:
        verbose_name = "Experience"
        
    def __str__(self):
        return self.experience_name    
        

src/myportfolio/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
import datetime


from .formulaire import PortfolioForm

from .models import  Experiences, Home, About, Profile, Category, Skills, Portfolio
from django.contrib import messages


def index(request):
    # HOME

    home = Home.objects.latest('updated')

    # About
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter()
    
    # Skills
    categories = Category.objects.all()

    # Portfolio
    portfolios = Portfolio.objects.all()

    context = {
        "home": home,
        "about": about,
        "profiles": profiles,
        "categories": categories,
        "portfolios": portfolios,

    }
    
    return render(request, "index.html", context)

    

def send_message(request):

    if request.method == "POST":
        form = PortfolioForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Votre message a été envoyé avec succès !")
            return HttpResponseRedirect(request.path)

    else:
        form = PortfolioForm
    return render(request, "contact/contact.html", {"form": form})


def experiences(request):
    experience = Experiences.objects.all()
    return render(request, "exp.html", {"experience": experience})
    





















    

src/myportfolio/templates/brouillons.html
<div class="contact__inputs">
    <input type="text" placeholder="Nom" name="" class="contact__input">
    <input type="mail" placeholder="Email" name="" class="contact__input">
</div>

<textarea name="" id="" cols="0" rows="10" class="contact__input" placeholder="Message"></textarea>

<input type="submit" value="Envoyer" class="contact__button">



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <h1>Contactez-moi</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>
    
</body>
</html>


from django import forms
from myportfolio.models import PorfolioMessage

class PortfolioForm(forms.ModelForm):
    class Meta:
        model = PorfolioMessage
        fields = ["nom", "email", "message"]


        
def send_messaage(request):
if request == "POST":
    form = PortfolioForm(request.POST)
    if form.is_valid():
        form.save()
    return HttpResponseRedirect (request.Path)
        
else:
    form = PortfolioForm()
return render(request, "index.html", {"form":form}) 



<input type="text" placeholder="Nom" class="contact__input" name="nom" value="{{ form.nom}}">
<input type="mail" placeholder="Email" class="contact__input" name="email" value="{{ form.nom}}">
<textarea name="message" id="" cols="0" rows="10" class="contact__input" placeholder="Message" value="{{ form.message}}"></textarea>

views


def send_message(request):
    if request == 'POST':
        form = PortfolioForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect (request.Path)

    else:
        form = PortfolioForm()
    return render(request, 'contact.html', {"form": form})


    if request == "POST":
        nom = request.POST["nom"]
        email = request.POST["email"]
        message = request.POST["message"]
        return render(request, "contact.html", )

    else:
        return render(request, "contact.html", {"form": "form"})


formulaire


  submitted = False
    if request.method == "POST":
        form = PortfolioForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/send_message?submitted')
    else:
        form = PortfolioForm
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'contact/contact.html', {'form': form, 'submitted': submitted})




contact

  <!--===== CONTACT =====-->
            <section class="contact section" id="contact">

                <h2 class="section-title">Contact </h2>

                <div class="contact__container bd-grid bg-light">
                    <div class="contact__info">
                        <h3 class="contact__subtitle">Email</h3>
                        <span class="contact__text">sirikibamba68@gmail.com</span>

                        <h3 class="contact__subtitle">Phone</h3>
                        <span class="contact__text">+225 07 09 59 70 30</span> <br/>
                        <span class="contact__text">+225 05 44 20 57 16</span>

                        <h3 class="contact__subtitle">Adress</h3>
                        <span class="contact__text">Abidjan Ivory Coast </span>
                    </div>

                       <form action="" class="contact__form" method=POST >
                            {% csrf_token %}
                            {{ form.as_p}}
                            <button type="submit" class="btn btn-primary">Envoyer</button>
                       </form>

                </div>

            </section>

  <span class="skills__name">PHP</span>
                    <span class="skills__name">ANGULAR</span>
                    <span class="skills__name">SQL</span>
                    <span class="skills__name">Git</span>


                    <h3 class="skills__subtitle">Design</h3>
                    <span class="skills__name">FIGMA</span>
                    <span class="skills__name">SKETCH</span>




 <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Contact</h2>

                <div class="contact__container bd-grid">
                    <div class="contact__info">
                        <h3 class="contact__subtitle">EMAIL</h3>
                        <span class="contact__text">sirikibamba68@gmail.com</span>

                        <h3 class="contact__subtitle">PHONE</h3>
                        <span class="contact__text">+225 07 09 59 70 30</span>
                         <br/>
                        <span class="contact__text">+225 05 44 20 57 16</span>

                        <h3 class="contact__subtitle">ADRESS</h3>
                        <span class="contact__text">My contry</span>
                    </div>

                    <form action="" class="contact__form" method="POST">
                        {% csrf_token %}
                        <div class="contact__inputs">
                            <input type="text" placeholder="Name"  id="nom" name="nom" class="contact__input" required>
                            <input type="email" placeholder="Email"   id="email" name="email" class="contact__input" required>

                        </div>

                        <textarea name="message" id="message" cols="0" rows="10" class="contact__input" required></textarea>


                        <input type="submit" value="Envoyer" class="contact__button">
                    </form>
                </div>
            </section>

src/myportfolio/templates/contact/contact.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
         <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
         <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} "/>
        <title>Portfolio responsive complete</title>

    </head>
<body>



      <!--===== CONTACT =====-->
            <section class="contact__section " id="contact ">
                {% for msg in messages %}
                        <p class="text-success ml-3 " style="margin-left: 50px;">{{msg}}</p>
                {% endfor %}

                <h2 style="text-align: center;text-decoration: underline blue  ;">Contact</h2>
                <a href="{% url 'index' %}"><button class="btn btn-primary" style="margin-left: 100px;"> Retour</button></a>
                <div class="contact__container mt-3 bd-grid bg-success p-2 text-dark bg-opacity-25 rounded-3  ">

                    <div class="contact__info " >
                        <h3 class="contact__subtitle">EMAIL</h3>
                        <span class="contact__text">sirikibamba68@gmail.com</span>

                        <h3 class="contact__subtitle">PHONE</h3>
                        <span class="contact__text">+225 07 09 59 70 30</span>
                        <br/>
                        <span class="contact__text">+225 05 44 20 57 16</span>

                        <h3 class="contact__subtitle">ADRESS</h3>
                        <span class="contact__text">Côte d'Ivoire</span>
                    </div>

                    <form action="" class="contact__form" method="POST">
                        {% csrf_token %}
                        <div class="contact__inputs">
                            <input type="text" placeholder="Name"  name="nom" class="contact__input" required >
                            <input type="mail" placeholder="Email" name="email" class="contact__input" required>

                        </div>
                        <textarea name="message" placeholder="Message"  cols="0" rows="10" class="contact__input" required></textarea>
                          <input type="submit" value="Envoyer" class="contact__button">


                    </form>
                </div>
            </section>
     <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

src/myportfolio/templates/exp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ===== CSS ===== -->
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

    <!-- ===== BOX ICONS ===== -->
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

    <title>Mon portfolio personnel</title>
</head>
<body>
   

    <main class="l-main">
    <!--===== ABOUT =====-->
    <section class="about section" id="about">
        <h2 class="section-title">Mes Experiences Professionnelles</h2>

        <div class="about__container bd-grid">
            {% for expe in experience %}
            <div class="about__img">
                <img src="{{ expe.experience_img.url}}" alt=""> 
            </div>

            <div> 
                <h2 class="about__subtitle">{{ expe.experience_name }}</h2>
                <span class="about__profession">{{expe.experience_Post}}</span>
                <p class="about__text">{{ expe.experience_description}}</p>

                
            </div>
            {% endfor %}
        </div>
    </section>


    </main>
     <!--===== SCROLL REVEAL =====-->
     <script src="https://unpkg.com/scrollreveal"></script>

     <!--===== MAIN JS =====-->
     <script src="{% static 'assets/js/main.js' %}"></script>    
</body>
</html>

src/myportfolio/templates/index.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Mon portfolio personnel</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                <div>
                    <a href="#" class="nav__logo">{{home.name}}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Accueil</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">A propos</a></li>
                        <li class="nav__item"><a href="{% url 'experiences' %}" class="nav__link">Expériences Professionnelle</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Compétences</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Mes Projets</a></li>
                        <li class="nav__item"><a href="{% url 'send_message' %} " class="nav__link ">Contact</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home" id="home">
                <div class="home__container bd-grid">
                    <h1 class="home__title"><span>{{home.greetings_1}}</span><br>{{home.greetings_2}}</h1>

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>

                    <img src="{{ home.picture.url}}" alt=""  class="home__img" style="height: 660px; width: 460px;">
                </div>
            </section>
            
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">A propos</h2>

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <img src="{{ about.profile_img.url}}" alt=""> 
                    </div>

                    <div> 
                        <h2 class="about__subtitle">{{ about.heading }}</h2>
                        <span class="about__profession">{{about.career }}</span>
                        <p class="about__text">{{ about.description}}</p>

                        <div class="about__social">
                            <a href="https://www.linkedin.com/in/bamba-siriki-722093209/" class="about__social-icon"><i class='bx bxl-linkedin' ></i></a>
                            <a href="https://github.com/bamba8?tab=repositories" class="about__social-icon"><i class='bx bxl-github' ></i></a>
                            <a href="https://gitlab.com/dashboard/projects" class="about__social-icon"><i class='bx bxl-gitlab' ></i></a>
                             <a href="https://www.facebook.com/profile.php?id=100044361520359" class="footer__social"><i class='bx bxl-facebook' ></i></a>
                        </div>
                    </div>
                </div>
            </section>

          <!--===== SKILLS =====-->
          <section class="skills section" id="skills">
            <h2 class="section-title">Compétences</h2>

            <div class="skills__container bd-grid">
                <div class="skills__box">

                    <div class="skills__box">
                    {% for category in categories%}
                     <h3 class="skills__subtitle">{{category.name}}</h3>

                        {% for skills in category.skills_set.all %}
                            <span class="skills__name">{{skills.skill_name}}</span>
                        {% endfor%}
                    {% endfor%}

                    </div>
                </div>

            </div>
        </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
                <h2 class="section-title">Mes Projets</h2>

                <div class="portfolio__container bd-grid">
                    {% for portfolio in portfolios %}
                    <div class="portfolio__img">
                        <img src="{{portfolio.image.url}}" alt="">

                        <div class="portfolio__link">
                            <a href="{{portfolio.link}}" class="portfolio__link-name" >Voir projet </a>
                        </div>

                    </div>
                    {% endfor%}
                </div>
            </section>


        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title">Bamba Siriki</h2>
                    <p class="footer__text">I'm Bamba Siriki and this is my personal website.</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Accueil</a></li>
                        <li><a href="#about" class="footer__link">A propos</a></li>
                        <li><a href="{% url 'experiences' %}" class="footer__link">Expériences Professionnelle</a></li>
                        <li><a href="#skills" class="footer__link">Compétences</a></li>
                        <li><a href="#portfolio" class="footer__link">Portfolio</a></li>
                        <li><a href="{% url 'send_message' %}" class="footer__link">Contact</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    <h2 class="footer__title">Suivez-moi sur :</h2>
                    <a href="https://www.linkedin.com/in/bamba-siriki-722093209/" class="about__social-icon"><i class='bx bxl-linkedin' ></i></a>
                    <a href="https://github.com/bamba8?tab=repositories" class="about__social-icon"><i class='bx bxl-github' ></i></a>
                    <a href="https://gitlab.com/dashboard/projects" class="about__social-icon"><i class='bx bxl-gitlab' ></i></a>
                    <a href="https://www.facebook.com/profile.php?id=100044361520359" class="footer__social"><i class='bx bxl-facebook' ></i></a>
                   
                </div>


            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>